use_field_init_shorthand = true
use_try_shorthand = true

# Unstable features--for future stabilization
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
hex_literal_case = "Lower"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
wrap_comments = true
format_code_in_doc_comments = true
empty_item_single_line = false
